### ISSUE TITLE
Empty response for powershell env vars

### ISSUE THREAD

**Issue by kdpuvvadi** [JanDeDobbeleer/aliae#110]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

in `env` block adding global env vars resulting in empty response. 

```yaml
env:
  - name: USER_NAME
    value: $ENV:USERNAME
    if: match .Shell "pwsh"
```

This works

but

```yaml
env:
  - name: ALIAE_CONFIG
    value: C:\Users\$($ENV:USERNAME)\.aliae.yaml
    if: match .Shell "pwsh"
```

this resulting in `C:\\Users\\\\.aliae.yaml`

is this even supported?

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell
