### ISSUE TITLE
Render Envs before Aliae so that Envs can be used in Aliae values

### ISSUE THREAD

**Issue by boldandbrad** [JanDeDobbeleer/aliae#195]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Currently the code in [init.go](https://github.com/JanDeDobbeleer/aliae/blob/main/src/core/init.go) seems to indicate that the aliae types get rendered to the executable script in the following order:

```go
    aliae.Paths.Render()
    aliae.Aliae.Render()
    aliae.Envs.Render()
    aliae.Scripts.Render()
```

The problem with this is that if a user specifies and ENV and then tries to use it in an alias value, it isn't yet set.

For example:

```yaml
# aliae.yaml

env:
  name: DOTFILES
  value: /Users/user_name/dotfiles

aliae:
  name: dots
  value: cd $DOTFILES
```

The `dots` name ends up just be aliased to `cd ` because `$DOTFILES` is not yet set.

I propose Envs should be rendered first so that they can be used in all of the other types. The rendering order should be as follows:

- Envs
- Paths
- Aliae
- Scripts
