### ISSUE TITLE
Links including a template or explicit env variable are skipped

### ISSUE THREAD

**Issue by boldandbrad** [JanDeDobbeleer/aliae#230]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Consider the following aliae.yaml:

```yaml

env:
  - name: DOTFILES
    value: $HOME/dotfiles

link:
  - name: ~/.foorc
    target: $DOTFILES/.foorc
  - name: ~/.barrc
    target: "{{ env 'DOTFILES' }}/.barrc"
  - name: ~/.bazrc
    target: "{{ .Env.DOTFILES }}/.bazrc"
  - name: ~/.waldorc
    target: path/to/dotfiles/.waldorc
```

Only `.waldorc` actually gets linked. The others get skipped.

> As an aside, I don't know what the difference between `{{ env "DOTFILES" }}` and `{{ .Env.DOTFILES }}` or which is correct since they are both referenced in the docs. Regardless, for this example they get skipped just the same.

I believe the reason for the skip is due to a check done in [link.go->string()](https://github.com/JanDeDobbeleer/aliae/blob/2639f290b58d709b7732e44f4c71bd1080b1d654/src/shell/link.go#L27), where we check that the link doesn't already exist and that the target DOES exist.

I believe it isn't correctly expanding the templates or the explicit `$VAR` reference before checking the `target` path, so of course the target does not exist. 

For a similar reason, I think a link with a `name` that includes a template will always think the link doesn't already exist, making the check mute. Though this is less of a problem since `ln` on linux/unix handles overriding existing links gracefully.

I'm not sure what a clean fix for this is, because theoretically the check, if any, should be done AFTER aliae processes envs so that they exist to be expanded.

A naive solution would be to just remove the check entirely, because at least on linux/unix systems, overriding links is graceful as mentioned above, and creating links to a non-existent target, though not ideal, does not break system state.

I'm using aliae version 0.26.0

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

zsh
