### ISSUE TITLE
Scripts field to spawn a command from Aliae itself

### ISSUE THREAD

**Issue by RuiNtD** [JanDeDobbeleer/aliae#266]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

It be would nice to have a `spawn` field on Scripts, that has aliae itself spawn a process. Main use-case would be for Nushell:

```yaml
- if: match .Shell "nu"
  spawn: oh-my-posh init nu
  value: source ~/.oh-my-posh.nu
```

For nu, putting both of these commands into value (which is actually [shown in docs](https://aliae.dev/docs/setup/script)) is actually incorrect syntax, since `source` is handled at parse and doesn't simply act as an "eval", so it just execs the results of the *last* `oh-my-posh init nu` if done that way.
