### ISSUE TITLE
Ability to create lists in Env

### ISSUE THREAD

**Issue by RuiNtD** [JanDeDobbeleer/aliae#31]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

The ability to create lists, similar to Path, easily cross-platform, like this:
```yml
env:
  - name: USERNAMES
    value: |
      dylan
      steve
      bob ross
```
```pwsh
# Windows
$Env:USERNAMES = "dylan;steve;bob ross"
# Linux
$Env:USERNAMES = "dylan:steve:boss ross"
```

Or, with an optional delimeter parameter:
```yml
env:
  - name: USERNAMES
    value: |
      dylan
      steve
      bob ross
    delimeter: ","
```
```pwsh
$Env:USERNAMES = "dylan,steve,bob ross"
```
