### ISSUE TITLE
Existance check of a file

### ISSUE THREAD

**Issue by trajano** [JanDeDobbeleer/aliae#60]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Something like
```
ssh-agent: 
  enabled: true
```
which maps to something along the lines of

```
script:
  - value: |
      eval $( ssh-agent )
  - if: 
      - ssh-agent executable is available
      - SSH_AUTH_SOCK env var is not set
```

Other options
```
ssh-agent: 
  force: true # ignore existing env var
  executables:  # override executable
    - executable: /opt/my/ssh-agent
       if: 
         - os == darwin etc.
    - executable: ssh-agent # default since it has no `if` may be omitted

```
