### ISSUE TITLE
`.` should be treated as a function

### ISSUE THREAD

**Issue by trajano** [JanDeDobbeleer/aliae#61]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I have the followubg config

```yaml
---
alias:
  - name: .
    value: eval "$(aliae init bash)"
```

in bash it generates

```bash
alias .="eval \"$(aliae init bash)\""
```

but when I run `.` I get

> `alias .': invalid alias name

What should happen is it should generate

```
.() {
  eval "$(aliae init bash)"
}
```

**Comment by trajano** [comment]
Actually this one didn't even work

```
alias:
  - name: .
    value: eval "$(aliae init bash)"
    type: function
```
