### ISSUE TITLE
path should have an option to check for existence before adding.

### ISSUE THREAD

**Issue by trajano** [JanDeDobbeleer/aliae#62]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Something new and amazing!
```
path:
  - value: |
      {{ .Home }}/.local/bin
    ifExists: true # defaults to false
```
This will check that the directory is present before changing path.  It should be false by default to keep it speedy and in case the path is in a network drive which means it will slow startup if existence is checked.
