### ISSUE TITLE
git alias evaluates at the time of loading profile

### ISSUE THREAD

**Issue by harrhp** [JanDeDobbeleer/aliae#87]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

aliae config
```
alias:
  - name: db
    value: "!basename $(git symbolic-ref refs/remotes/origin/HEAD)"
    type: git
```

after reloading profile git config looks like this 
```
[alias]
db = "!basename "
```
or like this if reloaded in context of git repository
```
[alias]
db = !basename refs/remotes/origin/master
```
expected to see this
```
[alias]
db = !basename $(git symbolic-ref refs/remotes/origin/HEAD)
```

### What OS are you seeing the problem on?

Windows, Linux

### Which shell are you using?

bash, powershell
